language: php

sudo: required
dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3

before_install:
  - composer global require phpunit/phpunit ^7.0
  - sudo add-apt-repository ppa:ondrej/php -y
  - sh -e build/travis/scripts/libsodium.sh

before_script:
  - sh -e build/travis/scripts/pecl-libsodium.sh || true
  - composer update --dev

script:
  - /home/travis/.config/composer/vendor/bin/phpunit --configuration phpunit.travis.xml
