language: php

sudo: required
dist: trusty

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_install:
  - sudo add-apt-repository ppa:ondrej/php -y
  - sh -e build/travis/scripts/libsodium.sh

before_script:
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then pecl install libsodium; fi
  - composer update --dev

script:
  - phpunit --configuration phpunit.travis.xml
